### ISSUE TITLE
[Bug]: Setting one Tag will clear all other tags

### ISSUE THREAD

**Issue by rsy12** [kiwilan/php-audio#34]
### What happened?

I want only to update the genre tag.  But if I do this all other tags are cleared.
Is this possible to set only one tag to update ?

### How to reproduce the bug

If I do this in the following way:
$tag = $audio->update()->genre($newGenre)->save();
or
$tag = $audio->update()
						->tags([
							'genre' => $newGenre,
						])
  						->tagFormats(['id3v1','id3v2.4']) // optional
  						->save();
All tags are cleared:

After the update Call
eyeD3 03.Eat_the_Music.mp3 
/home/rsy/tmp/test/03.Eat_the_Music.mp3                                                                                                               [ 12.10 MB ]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 05:11	MPEG1, Layer III	[ 320 kb/s @ 48000 Hz - Stereo ]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.4:
title: 
artist: 
album: 
track: 		genre: Adult Alternative Pop (id None)

--- 
Before the update call:
eyeD3 03.Eat_the_Music.mp3 
/home/rsy/tmp/test/03.Eat_the_Music.mp3                                                                                                               [ 12.10 MB ]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 05:11	MPEG1, Layer III	[ 320 kb/s @ 48000 Hz - Stereo ]
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v2.3:
title: Eat the Music
artist: Kate Bush
album: The Red Shoes
album artist: Kate Bush
composer: Kate Bush
recording date: 1993
track: 3/12		genre: Adult alternative pop/rock (id None)
Lyrics: [Description: ] [Lang: eng]

FRONT_COVER Image: [Size: 226557 bytes] [Type: image/jpeg]
Description: 

### Package Version

3.0

### PHP Version

8.3.6

### Which operating systems does with happen with?

Linux

**Comment by ewilan-riviere** [comment]
Thanks for your feedback!
It is indeed normal for the genre to be overwritten during the update. It's simply a `string` field that's overwritten and replaced. Is it possible that you're using software to list genres that will separate them using a comma or a space?


However, your proposal is interesting. What kind of functionality would you like? A method like `addGenre()` that adds a new genre in front of or behind the current ones?
I also propose a second parameter to handle the separator such as a comma or a space.

Translated with DeepL.com (free version)

**Comment by ewilan-riviere** [comment]
Thanks for report!
Fixed in next major version this week.

**Comment by ewilan-riviere** [comment]
Can you try latest version and tell me if you can update your file?

**Comment by rsy12** [comment]
Hello, thanks for the fast response.
I have check the new code with my program. All works fine the changed genre is updated and all  other fields left untouched.
Thanks a lot for your work.
Cheers Reinhard

**Comment by ewilan-riviere** [comment]
Thanks for your feedback !
